### ISSUE TITLE
SVGs Not Showing On Snapshots

### ISSUE THREAD

**Issue by beanshearer** [percy/percy-ember#215]
- Our SVGs are located in the assets directory.
- The SVGs load correctly when serving in all environments including the test environment.
- Apparently the SVGs have never loaded in Percy snapshots.
- We use ember exam and testem to run the tests.

What I've tried so far:
- I've tried upping to the latest version of @percy/ember.
- I've tried renaming the svg file name to check is it was a caching problem.
- I've tried using the ember test helper `waitFor`.

Please let me know what else I should try or if you need anymore information.

**Comment by Robdel12** [comment]
Hey @beanshearer thanks for the issue! Would you be able to link to a build where this is happening? I'd like to download a snapshot to take a look (and figure out if it's an SDK issue or something larger) 

You could also send the link to `support@percy.io` if you won't want to link it publicly 👍

**Comment by beanshearer** [comment]
Thanks for the quick response. I'll send a link to support@percy.io now.

**Comment by knowerlittle** [comment]
Any updates on this we have the same issue?

**Comment by Robdel12** [comment]
This is usually SDK setup / support kind of issue -- you can either reach out to support @ percy.io or [open a Q&A discussion](https://github.com/percy/percy-ember/discussions/new) with verbose logs/as many details as you can provide to help us debug. 

If it turns out to be an SDK bug we'll deff create an issue from it and get a fix working ASAP 😃
