### ISSUE TITLE
Difference in screenshots: Github Actions run vs. Local run

### ISSUE THREAD

**Issue by twokul** [percy/percy-ember#340]
Hello! 👋 

I came across the difference in screenshots which I cannot explain. Maybe someone could land a hand or could help debug the issue?

I have created a fake change to trigger the build (change in the README file, does not impact the functionality, at all.)

When `percy exec` runs on Github Actions, it shows that the newly taken screenshots are different from the baseline. [Build Link](https://percy.io/fb19ea46/Iverson/builds/11232579/changed/630725325?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1440&widths=709%2C711%2C1440%2C2000).

When I run `percy exec` locally, there is no difference. [Build Link](https://percy.io/fb19ea46/Iverson/builds/11232454/unchanged/630718110?browser=chrome&viewLayout=side-by-side&viewMode=new&width=2000).

I have compared the environment, head & base commit and browser version - they are all the same.

In both cases, the same command is used `yarn percy exec yarn test:visual`; `yarn test:visual` is a shortcut for `ember test --filter='visual acceptance'`.

The only thing that is different is the `$PERCY_BRANCH` variable which I do not set in Github Actions. If I read the documentation correctly, I do not need to set it, it defaults to the current git branch.

**Comment by mixonic** [comment]
I believe the variable is set at https://github.com/percy/exec-action/blob/be2fc13289392ce70a89314173ae2a5632271189/src/index.js#L10 ?

**Comment by Robdel12** [comment]
Hey @twokul! This doesn't appear to have anything to do with the env vars or the action. FWIW, if you're using `@percy/cli` the GH action isn't needed anymore. [You can see an example of how to move away from the action here](https://github.com/percy/exec-action#deprecated)

Looking at the two builds, it looks like the inline attrs on the SVGs for the graph is changing. 

<img width="926" alt="image" src="https://user-images.githubusercontent.com/2072894/123982673-d955f180-d988-11eb-836d-d6c42a276762.png">

vs

<img width="909" alt="image" src="https://user-images.githubusercontent.com/2072894/123982727-e4a91d00-d988-11eb-8b28-52969bbd8914.png">

Notice the `width` attr changes from `width="89.31522369384766"` to `width="79.57142639160156"`

This could be "normal" (not known until now) flexing of the graphs between test runs _or_ it could be a test browser width/viewport difference between your local & CI. It appears the graphs are responsive so they'll change according to the browsers width, so that would have to be exactly the same across test runs

**Comment by twokul** [comment]
@Robdel12 thanks for the response! A few follow up questions.

> Looking at the two builds, it looks like the inline attrs on the SVGs for the graph is changing.

I wish I could do this sort of debugging locally 😄 

> This could be "normal" (not known until now) flexing of the graphs between test runs

How does one go about stabilising the screenshots in this case?

> it could be a test browser width/viewport difference between your local & CI.

This is a bit confusing to me. Given that the same commands are used to run Percy tests & all the settings are the same, why would there be a difference in width/viewport? 🤔 My understanding was that they should be the same.

Thanks again!

**Comment by Robdel12** [comment]
> I wish I could do this sort of debugging locally

I'm hoping we introduce debugging tools this year -- it's been coming up a bunch in planning (I've been pushing hard for it). You could use the download HTML option, but admittedly it's not very useful (it's just HTML, no assets)

<img width="313" alt="download-html" src="https://user-images.githubusercontent.com/2072894/123988890-01941f00-d98e-11eb-9937-b45da7a6e459.png">

 
> why would there be a difference in width/viewport?

I'm not sure, Percy doesn't have any insight into that. That's the Ember test runner / application / test setup -- we're just capturing the exact state of the DOM when `percySnapshot` is called. Sometimes it's something like scrollbars present locally vs not in CI (or vice versa). That _could_ cause a 10px diff.

**Comment by twokul** [comment]
@Robdel12 I re-ran GH action using a different OS (macOS this time.) and all the differences in SVG `text` width & positioning are gone. The only difference that I see is font rendering which I guess makes sense? [Build Link](https://percy.io/fb19ea46/Iverson/builds/11260192/changed/632364735?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1440&widths=709%2C711%2C1440%2C2000).

Is there a difference between how SVG is rendered by Chrome on Linux vs. Mac?

**Comment by mixonic** [comment]
@Robdel12 and team is there a follow-up possible on the mac vs. Linux environments?
